# -*- coding: utf-8 -*-
"""asem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMYV2xK4AMKqkiImGSn8vM2DBRElCLfD

"""## Importing Packages"""

import numpy as np
from aomt.util import get_vertices_density, save_mesh

"""## Building Edge Augmented Matrix

Edge Augmented Matrix is a **(#edges x 8) matrix**, its columns are as follows: </br>
1. **Columns {0, 1}:** Indices of the first and second vertices of the edge.
2. **Columns {2, 3}:** Indices of the 2 vertices such that if each is combined with the edge, a triangle in the mesh is formed.
3. **Columns {4, 5}:** Areas of the Two Triangles formed by the vertices in the previous 2 columns and the edge respectively.
4. **Columns {6, 7}:** Densities of the Two Triangles formed by the vertices in the previous 2 columns and the edge respectively.

### a Function to build Adjacency Matrix for the Mesh
"""

def build_adj_matrix(mesh_faces, num_vertices):
  adj_matrix = np.zeros((num_vertices, num_vertices), dtype=bool)

  def fill_adj_matrix(face):
    v1, v2, v3 = face[0], face[1], face[2]
    adj_matrix[v1, v2], adj_matrix[v1, v3], adj_matrix[v2, v3] = True, True, True
    adj_matrix[v2, v1], adj_matrix[v3, v1], adj_matrix[v3, v2] = True, True, True

  np.apply_along_axis(fill_adj_matrix, axis=1, arr=mesh_faces)
  return adj_matrix

"""### a Function to build the first 4 comlums in Edge Augmented Matrix"""

def build_edge_aug_matrix_f4(adj_matrix, mesh_faces):
  edge_aug_matrix = []
  row_indices, col_indices = np.where(adj_matrix)
  edges = np.vstack([row_indices, col_indices]).T
  edges = edges[edges[:, 0] < edges[:, 1]]

  def get_triangle_vertices(edge):
    common_vertices = adj_matrix[edge[0]] & adj_matrix[edge[1]]
    if np.sum(common_vertices) > 1: # we have two triangles sharing this edge
      possible_face_heads = np.where(common_vertices)[0]
      e0_repeat = np.full_like(possible_face_heads, edge[0])
      e1_repeat = np.full_like(possible_face_heads, edge[1])

      possible_faces = np.column_stack((e0_repeat, e1_repeat, possible_face_heads))
      possible_faces = np.sort(possible_faces, axis=1)
      face_indices = np.where(np.all(possible_faces[:, None, :] == mesh_faces, axis=-1))[0]

      if(len(face_indices) > 1):
        x = np.array(np.hstack([edge, possible_face_heads[face_indices]])[:])
        edge_aug_matrix.append(x)

  np.apply_along_axis(get_triangle_vertices, axis=1, arr=edges)
  return np.array(edge_aug_matrix)

"""### a Function to compute columns 4 and 5 in Edge Augmented Matrix"""

compute_face_area = lambda v1, v2, v3: 0.5 * np.linalg.norm(np.cross(v2 - v1, v3 - v1))

def build_edge_aug_matrix_4_5(edge_aug_matrix, vertices):
  def compute_entry_4_5(row):
    v1, v2 = vertices[int(row[0])], vertices[int(row[1])]
    v3, v4 = vertices[int(row[2])], vertices[int(row[3])]
    row[4:6] = np.array([compute_face_area(v1, v2, v3), compute_face_area(v1, v2, v4)])

  np.apply_along_axis(compute_entry_4_5, axis=1, arr=edge_aug_matrix)
  return edge_aug_matrix[:, 4:6]

"""### a Function to compute columns 6 and 7 in Edge Augmented Matrix"""

def build_edge_aug_matrix_6_7(edge_aug_matrix, vertices_densities):
  def compute_entry_6_7(row):
    d_v1, d_v2 = vertices_densities[int(row[0])], vertices_densities[int(row[1])]
    d_v3, d_v4 = vertices_densities[int(row[2])], vertices_densities[int(row[3])]
    row[6:8] = np.array([(d_v1 + d_v2 + d_v3) / 3, (d_v1 + d_v2 + d_v4) / 3])

  np.apply_along_axis(compute_entry_6_7, axis=1, arr=edge_aug_matrix)
  return edge_aug_matrix[:, 6:8]

"""### a Facade Function to build Edge Augmented Matrix"""

def build_edge_aug_matrix(adj_matrix, vertices, faces, vertices_densities):
  edge_aug_matrix_mini = build_edge_aug_matrix_f4(adj_matrix, faces)
  edge_aug_matrix = np.zeros((edge_aug_matrix_mini.shape[0], 8))
  edge_aug_matrix[:, :4] = edge_aug_matrix_mini.reshape((edge_aug_matrix_mini.shape[0], 4))
  edge_aug_matrix[:, 4:6] = build_edge_aug_matrix_4_5(edge_aug_matrix, vertices)
  edge_aug_matrix[:, 6:8] = build_edge_aug_matrix_6_7(edge_aug_matrix, vertices_densities)
  return edge_aug_matrix

"""### Compute Spherical Conformal Parameterization"""

def compute_spherical_conformal_parameterization(off_file_path):
  import subprocess
  octave_command = ['octave', '-W', 'linear_spherical_conformal_map/demo.m', off_file_path]
  subprocess.run(octave_command)
  g = []
  with open('linear_spherical_conformal_map/spherical_conformal_map_output.txt', 'r') as file:
    num_vertices = file.readline()
    # Extract the number of vertices from the first line
    num_vertices = int(num_vertices.strip())
    print(f"Number of vertices: {num_vertices}")
    for line in file:
        g.append(line.split())
  return np.array(g, dtype=np.float64)

ε = 1e-6

stereo_graphic_projection = lambda v: v[0] / (1 - v[2]) + v[1] / (1 - v[2]) * 1j if v[2] != 1 else 1/ε + 1j/ε

def inv_stereo_graphic_projection(complex_num):
  u = complex_num.real
  v = complex_num.imag
  norm_sqr = abs(complex_num) ** 2
  return np.array([2 * u / (norm_sqr + 1), 2 * v / (norm_sqr + 1), (norm_sqr - 1) / (norm_sqr + 1)])

def cotan_α(vi, vj, vk):
  v1, v2 = vi - vk, vj - vk
  dot_product = np.dot(v1, v2)
  cos = dot_product / ((np.linalg.norm(v1) + ε) * (np.linalg.norm(v2) + ε))
  angle = np.arccos(np.clip(cos, -1.0, 1.0))
  tan = np.tan(angle)
  if tan == 0:
    tan = ε
  return 1 / tan

def stretch_factor(ρ, area, f, i, j, k):
   f_area = compute_face_area(f[i], f[j], f[k])
  #  print('inside stretch_factor func', f_area, ρ, area, ρ * area / f_area)
   if f_area == 0:
    return ρ * area / ε
   return ρ * area / f_area

dirichlet_energy = lambda L, f: np.trace(np.dot(np.dot(f.T, L), f)) / 2.0

def compute_laplacian_matrix(num_vertices, edge_aug_matrix, f, ε=1e-6):
  L = np.zeros((num_vertices, num_vertices))
  count = 0
  count_pos = 0
  def compute_Lij(row):
    nonlocal count
    nonlocal count_pos
    i, j, k, l, area1, area2, ρ1, ρ2 = row
    i, j, k, l = map(int, [i, j, k, l])

    L[i, j] = cotan_α(*f[[i, j, k]]) / (stretch_factor(ρ1, area1, f, i, j, k) + ε) + cotan_α(*f[[i, j, l]]) / (stretch_factor(ρ2, area2, f, i, j, l) + ε)
    L[i, j] *= -0.5
    if i != j and L[i, j] > 0:
      L[i, j] = 0
    L[j, i] = L[i, j]
  np.apply_along_axis(compute_Lij, axis=1, arr=edge_aug_matrix)
  return L + -1 * np.diag(np.sum(L, axis=1))

def shuffle_L_h(L, h, r=1.2):
  norms = abs(h)
  shuffled_indices = np.argsort(norms, kind='mergesort')
  shuffled_L = L[shuffled_indices]
  shuffled_h = h[shuffled_indices]
  reverse_mapping = np.argsort(shuffled_indices)
  return shuffled_L, shuffled_h, np.argmax(abs(shuffled_h) >= r), reverse_mapping

def inv_stereo_graphic_projection_all_points(h):
  vectorized = np.vectorize(inv_stereo_graphic_projection, signature='()->(n)')
  return vectorized(h)

"""## ASEM Algorithm Main Function"""

def asem(mesh_vertices, mesh_faces, image_density_map, g=None, off_file_path=None, ε=1e-6, r=1.2):
  num_vertices = mesh_vertices.shape[0]
  vertices_densities = get_vertices_density(image_density_map, mesh_vertices)
  adj_matrix = build_adj_matrix(mesh_faces, mesh_vertices.shape[0])
  edge_aug_matrix = build_edge_aug_matrix(adj_matrix, mesh_vertices, mesh_faces, vertices_densities)
  if g is None:
    # off_file_path of original genus-0 mesh to compute conformal mapping
    g = compute_spherical_conformal_parameterization(off_file_path)
    save_mesh(g, mesh_faces, '/content/asem_mesh.off')
  h = np.apply_along_axis(stereo_graphic_projection, axis=1, arr=g)
  L = compute_laplacian_matrix(num_vertices, edge_aug_matrix, g)
  dir_energy = dirichlet_energy(L, g)
  print('dirichlet energy =', dir_energy)
  δ = np.inf
  min_energy = dir_energy
  while δ > ε:
    np.divide(h, abs(h) ** 2 + ε, out=np.full_like(h, 1/ε + 1j/ε), where=(abs(h) != 0))
    print("h values: ", np.median(abs(h)), np.mean(abs(h)), np.min(abs(h)), np.max(abs(h)));
    tempL, h, b_first_index, mapping = shuffle_L_h(L, h, r)
    Lii, Lib = tempL[:b_first_index, :b_first_index], tempL[:b_first_index, b_first_index:]
    hi, hb = h[:b_first_index], h[b_first_index:]
    hi, *_ = np.linalg.lstsq(Lii, -np.dot(Lib, hb), rcond=None)
    h[:b_first_index] = hi
    h = h[mapping]
    print(f'first index {b_first_index}, no of samples {g.shape[0]}')
    g = inv_stereo_graphic_projection_all_points(h)
    new_dir_energy = dirichlet_energy(L, g)
    print('dirichlet energy =', new_dir_energy)
    δ = dir_energy - new_dir_energy
    print('δ =', δ)
    dir_energy = new_dir_energy
    L = compute_laplacian_matrix(num_vertices, edge_aug_matrix, g)
    if new_dir_energy < min_energy:
      min_energy = new_dir_energy
      save_mesh(g, mesh_faces, '/content/asem_mesh.off')
  return g