# -*- coding: utf-8 -*-
"""cehe_algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MMKBCdj7VbsHdErYRgrsOAgtfSKKtG0q

## Importing Necessary Libraries
"""

import numpy as np
import nibabel as nib
import pandas as pd
from numpy.lib.stride_tricks import sliding_window_view

"""## Some Neighborhood Metrics Implementation"""

average_fn = lambda window, nb_sz : np.sum(window - window[nb_sz // 2, nb_sz // 2, nb_sz // 2], axis=(1, 2, 3)) / (nb_sz ** 3 - 1)

inverted_average_fn = lambda window, nb_sz: window[:, nb_sz // 2, nb_sz // 2, nb_sz // 2] - average_fn(window, nb_sz)

neighbourhood_voting_fn = lambda window, nb_sz : np.count_nonzero(window < window[nb_sz // 2, nb_sz // 2, nb_sz // 2], axis=(1, 2, 3))

"""## CEHE Algorithm Implementation"""


def cehe(image, metric, m, D):
  l, w, c = image.shape
  B = (l * w * c) / D

  i, j, k = np.indices((l, w, c))
  i, j, k = i.reshape((-1)), j.reshape((-1)), k.reshape(-1)
  g = image[i, j, k]
  padding = ((m // 2, m // 2), (m // 2, m // 2), (m // 2, m // 2))
  padded_array = np.pad(image, padding, mode='constant', constant_values=0)
  windows = sliding_window_view(padded_array, (m, m, m))
  windows = windows.reshape((-1, m, m, m))

  λ = metric(windows, m)
  del windows

  df = pd.DataFrame({'g': g, 'λ': λ.flatten(), 'i': i, 'j': j, 'k': k})
  grouped_lists = df.groupby(['g', 'λ']).agg({
    'i': list,
    'j': list,
    'k': list
  }).reset_index()
  list_i = grouped_lists['i'].tolist()
  list_j = grouped_lists['j'].tolist()
  list_k = grouped_lists['k'].tolist()

  del df

  index = 0
  histogram_i, histogram_j, histogram_k = [[]], [[]], [[]]
  for it in range(len(list_i)):
    if B - len(histogram_i[index]) < len(list_i[it]) / 2:
      histogram_i.append([]);
      histogram_j.append([]);
      histogram_k.append([])
      index += 1
    histogram_i[index] += list_i[it];
    histogram_j[index] += list_j[it];
    histogram_k[index] += list_k[it]

  offset = D // (index + 1)

  enhanced_image = np.zeros(image.shape, dtype=image.dtype)
  g = 0
  for it in range(len(histogram_i)):
    enhanced_image[histogram_i[it], histogram_j[it], histogram_k[it]] = g
    g += offset
  return enhanced_image

"""## Image Normalization & Getting Image Density Map"""

# Normalizing Image Array
normalize_img_arr = lambda image_arr: (image_arr - np.mean(image_arr)) / np.std(image_arr)

# Getting Density Map
get_density_map = lambda enhanced_image, gamma: np.exp(gamma * normalize_img_arr(enhanced_image.get_fdata()))

