# -*- coding: utf-8 -*-
"""CEHE-Algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MMKBCdj7VbsHdErYRgrsOAgtfSKKtG0q

## Importing Necessary Libraries
"""

import numpy as np
import nibabel as nib

"""## Some Neighborhood Metrics Implementation"""

range_fn = lambda i, length, offset: (max(0, i - offset), min(length, i + offset + 1))

def ranges(point, neighborhood_size, shape):
  l, w, c = shape
  offset = neighborhood_size // 2
  min_x, max_x = range_fn(point[0], l, offset)
  min_y, max_y = range_fn(point[1], w, offset)
  min_z, max_z = range_fn(point[2], c, offset)
  return min_x, max_x, min_y, max_y, min_z, max_z


def average_fn(point, image, neighborhood_size):
  min_x, max_x, min_y, max_y, min_z, max_z = ranges(point, neighborhood_size, image.shape)
  return (np.sum(image[min_x: max_x, min_y: max_y, min_z: max_z]) - image[point]) / (neighborhood_size ** 3 - 1)

inverted_average_fn = lambda point, image, neighborhood_size: image[point] - average_fn(point, image, neighborhood_size)

def neighbourhood_voting_fn(point, image, neighborhood_size):
  min_x, max_x, min_y, max_y, min_z, max_z = ranges(point, neighborhood_size, image.shape)
  return np.count_nonzero(image[min_x: max_x, min_y: max_y, min_z: max_z] < image[point])

"""## CEHE Algorithm Implementation"""

def CEHE(image, metric, m, D):
  temp_histogram = {}
  l, w, c = image.shape
  B = (l * w * c) / D
  for k in range(c):
    for i in range(l):
      for j in range(w):
        g = image[i, j, k]
        λ = metric((i, j, k), image, m)
        if not (g, λ) in temp_histogram:
          temp_histogram[g, λ] = []
        temp_histogram[g, λ].append((i, j, k))

  keys = list(temp_histogram.keys())
  keys.sort()
  j = 0
  histogram = [[]]
  for g, λ in keys:
    if B - len(histogram[j]) < len(temp_histogram[g, λ]) / 2:
      histogram.append([])
      j += 1
    histogram[j] += temp_histogram[g, λ]
  offset = D // (j + 1)

  enhanced_image = np.zeros(image.shape, dtype=image.dtype)
  g = 0
  for points in histogram:
    for point in points:
      enhanced_image[point] = g
    g += offset

  return enhanced_image

"""## Image Normalization & Getting Image Density Map"""

# Normalizing Image Array
normalize_img_arr = lambda image_arr: (image_arr - np.mean(image_arr)) / np.std(image_arr)

# Getting Density Map
get_density_map = lambda enhanced_image, gamma: np.exp(gamma * normalize_img_arr(enhanced_image.get_fdata()))

"""## Example on how to do CEHE on an MRI Scan then get density map:

"""

mri_image = nib.load("/content/BraTS2021_00000_flair.nii.gz")
image_arr = mri_image.get_fdata()
enhanced_image_arr = CEHE(image_arr, neighbourhood_voting_fn, 3, 65536)
enhanced_image = nib.Nifti1Image(enhanced_image_arr, affine=np.eye(4))

density_map = get_density_map(enhanced_image, 1)